version: "3.4"

services:
  web:
    build:
      context: .
      args:
        - MOODLE_VERSION=MOODLE_403_STABLE
        - MOODLE_CODECHECKER_VERSION=5.0.4
        - MOODLE_PLUGIN_RELATIVE_PATH=report/usercoursecompletions
    ports:
      - 8080:80
    environment:
        - MOODLE_DATABASE=moodle
        - MOODLE_DATABASE_USER=moodle
        - MOODLE_DATABASE_PASSWORD=secret
    volumes:
      - .:/usr/local/src
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
      image: mariadb:10.6.7
      command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
              --skip-log-bin
      environment:
        - MYSQL_DATABASE=moodle
        - MYSQL_USER=moodle
        - MYSQL_PASSWORD=secret
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      volumes:
        - /var/lib/mysql

  selenium:
    image: "selenium/standalone-firefox:4.17.0-20240123"
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900

