apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  containers:
  - name: gcloud
    image:  gcr.io/cloud-builders/gcloud
    command: ["tail", "-f", "/dev/null"]
  - name: composer
    image: composer:2
    command: ["tail", "-f", "/dev/null"]
  - name: git
    image: gcr.io/cloud-builders/git
    command: ["tail", "-f", "/dev/null"]
  - name: docker-compose
    image: gcr.io/veri-cluster/docker-compose
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock

